version: '3'

services:
  chrome:
    image: justinribeiro/chrome-headless
    cap_add:
      - SYS_ADMIN
    restart: always
    ports:
      - "9222:9222"

  cassandra:
    #image: cassandra
    build: ./storage/cassandra
    restart: always
    environment:
      # define cluster topology
      - CASSANDRA_CLUSTER_NAME=dfk-db
      - CASSANDRA_DC=dfk-east
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

      # define gossip entrypoints
      #- CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_SEEDS=cassandra 

      # define heap size for local development
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=100M

      # open JMX port for access by Reaper
      # WARNING: this is unsafe in production without proper firewall settings
      - LOCAL_JMX=yes    

    ports:
      - "7199:7199" # JMX
      - "7000:7000" # cluster communication
      - "7001:7001" # cluster communication (SSL)
      - "9042:9042" # native protocol clients
      - "9160:9160" # thrift clients
    volumes:
#      - ./cassandra/config/collectd.cassandra.conf:/etc/collectd/collectd.conf
#     - ./cassandra/config/graphite.cassandra.yaml:/etc/cassandra/graphite.yaml
#     - ./cassandra/config/filebeat.yml:/etc/filebeat/filebeat.yml
#      - ./cassandra/config/prometheus.yml:/prometheus/prometheus.yml
      - ./storage/cassandra/db:/var/lib/cassandra
      - ./storage/cassandra/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    

  testserver:
    #build: ./testserver
    image: slotix/dfk-testserver
    environment:
      - DFK_TEST=testserver:12345
    ports:
      - "12345:12345"
    depends_on:
      - chrome
    restart: always
  