service: todo
package:
  artifact: package.zip
provider:
  name: aws
  runtime: python2.7
  stage: ${env:ENV}
  region: ${env:AWS_REGION}
functions:
  create:
    handler: handler.Create
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: handler.List
    events:
      - http:
          path: todos
          method: get
          cors: true

  get:
    handler: handler.Get
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: handler.Update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: handler.Delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true