service: dfk
package:
  artifact: package.zip
provider:
  name: aws
  runtime: python2.7
  timeout: 10
  stage: ${env:ENV}
  region: ${env:AWS_REGION}
functions:
  fetch:
    handler: handler.Handler
    environment:
      SPLASH: ${env:SPLASH}
      SPLASH_TIMEOUT: ${env:SPLASH_TIMEOUT}
      SPLASH_RESOURCE_TIMEOUT: ${env:SPLASH_RESOURCE_TIMEOUT}
      SPLASH_WAIT: ${env:SPLASH_WAIT}
      SQS_QUEUE_URL: ${env:SQS_QUEUE_URL}
      SQS_AWS_REGION: ${env:SQS_AWS_REGION}
      SQS_MAX_RETRIES: 5
    events:
      - http:
          path: fetch
          method: post
          cors: true