[[constraint]]
  branch = "master"
  name = "github.com/eawsy/aws-lambda-go-net"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/mux"
